// enum que define uma propriedade usada para diferenciar os redirects no componente de anexos
export const waysEnum = Object.freeze({
  WAITING_ROOM: 'waitingRoom',
  MEDICINES: 'medicines',
  SCHEDULED_APPOINTMENTS: 'ScheduledAppointmentsAttachments',
  HAS_NO_PREFERENCE: 'hasNoPreference',
  WAITING_ROOM_SCHEDULED: 'waitingRoomScheduled',
  SCHEDULED_FROM_HOME: 'scheduledFromHome',
  SCHEDULE_FINISHED: 'ScheduleFinished',
  PERMISSIONS_IMMEDIATE: 'PermissionsImmediate',
  PERMISSIONS_SCHEDULED: 'PermissionsScheduled',
  PROFILE: 'Profile',
  MULTIPROFILE: 'Multiprofile',
});

export const reviewsEnum = Object.freeze({
  TERRIBLE: 'Péssimo',
  BAD: 'Ruim',
  INDIFFERENT: 'Bom',
  GOOD: 'Ótimo',
  GREAT: 'Excelente',
});

export const positiveReviewsEnum = Object.freeze({
  CONFIAVEL: 'CONFIAVEL',
  EDUCADO: 'EDUCADO',
  ATENCIOSO: 'ATENCIOSO',
  PONTUAL: 'PONTUAL',
  VALOR_JUSTO_POSITIVO: 'VALOR_JUSTO_POSITIVO',
  NAO_TRAVOU: 'NAO_TRAVOU',
  FACIL: 'FACIL',
  QUALIDADE_VIDEO_POSITIVO: 'QUALIDADE_VIDEO_POSITIVO',
  QUALIDADE_AUDIO_POSITIVO: 'QUALIDADE_AUDIO_POSITIVO',
});

export const negativeReviewsEnum = Object.freeze({
  PASSAR_CONFIANCA: 'PASSAR_CONFIANCA',
  SER_EDUCADO: 'SER_EDUCADO',
  SER_ATENCIOSO: 'SER_ATENCIOSO',
  SER_PONTUAL: 'SER_PONTUAL',
  VALOR_JUSTO_NEGATIVO: 'VALOR_JUSTO_NEGATIVO',
  TRAVAR_MENOS: 'TRAVAR_MENOS',
  FACILIDADE_NAVEGACAO: 'FACILIDADE_NAVEGACAO',
  QUALIDADE_VIDEO_NEGATIVO: 'QUALIDADE_VIDEO_NEGATIVO',
  QUALIDADE_AUDIO_NEGATIVO: 'QUALIDADE_AUDIO_NEGATIVO',
});

export const reasonsToCancel = Object.freeze({
  ESTOU_MELHOR: 'ESTOU_MELHOR',
  TENHO_COMPROMISSO: 'TENHO_OUTRO_COMPROMISSO',
  NAO_PRECISO_RETORNO: 'NAO_PRECISO_CONSULTA_RETORNO',
  AGENDEI_MAIS_PROXIMA: 'AGENDEI_CONSULTA_MAIS_PROXIMA',
  MARQUEI_PRESENCIAL: 'MARQUEI_CONSULTA_PRESENCIAL',
  ENCONTREI_MAIS_BARATA: 'ENCONTREI_CONSULTA_ONLINE_MAIS_BARATA',
  FOI_ENGANO: 'AGENDEI_POR_ENGANO',
  FIZ_PLANO_SAUDE: 'FIZ_PLANO_SAUDE',
  FUI_PARA_SUS: 'FUI_PARA_SUS',
});

export const AttendanceStatus = Object.freeze({
  CHAMADA_ATIVA: 'CHAMADA ATIVA',
  AGUARDANDO_ATEND: 'AGUARDANDO_ATENDIMENTO',
  ATENDI_INI: 'ATENDIMENTO_INICIADO',
  CHAMADA_INI: 'CHAMADA_INICIADA',
  CHAMADA_ENC: 'CHAMADA_ENCERRADA',
  CHAMADA_REINI: 'CHAMADA_REINICIADA',
  ATEND_CANC_MEDICO: 'ATENDIMENTO_CANCELADO_PELO_MEDICO',
  ATEND_CANC_ATRASO: 'ATENDIMENTO_CANCELADO_POR_ATRASO',
  ATEND_CONC: 'ATENDIMENTO_CONCLUIDO',
  ATEND_CANC_PACIENTE: 'ATENDIMENTO_CANCELADO_PELO_PACIENTE',
});

export const professionalTypesID = Object.freeze({
  MED: 'MEDICO',
  ENF: 'ENFERMEIRO',
  PSICO: 'PSICOLOGO',
  NUTRI: 'NUTRICIONISTA',
  DENT: 'DENTISTA',
  FISIO: 'FISIOTERAPEUTA',
  FONO: 'FONOAUDIOLOGO',
  ASSIS_SOC: 'ASSISTENTE_SOCIAL',
  ORIENT_ACAD: 'ACADEMICO',
});

export const specialtiesID = Object.freeze({
  ALERG_IMUNO_PED: 77,
  ANESTESIO: 20,
  CARDIO: 1,
  CIRURG_GERAL: 29,
  CIRURG_PLAST: '',
  CLINICA_GERAL: 2,
  DERMATOLOGIA: 11,
  ENDOCRINO: '',
  GASTROENT: 4,
  GASTROENT_PED: 69,
  GINEC_OBSTET: 6,
  INFECTO_PED: '',
  MASTOLOGIA: 31,
  NEUROCIRURG: 33,
  NEUROLOG: 3,
  NEUROLOG_PED: '',
  OFTALMOLOGIA: 14,
  ORTOPEDIA: '',
  OTORRINO: 15,
  PEDIATRIA: 5,
  PNEUMOLOGIA: 7,
  PSIQUIATRIA: 17,
  UROLOGIA: '',
});
