require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
# use_frameworks!

# Convert all permission pods into static libraries
pre_install do |installer|
  installer.pod_targets.each do |pod|
    if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-')
      def pod.build_type;
        # Uncomment one line depending on your CocoaPods version
        Pod::BuildType.static_library # >= 1.9
       # Pod::Target::BuildType.static_library # < 1.9
      end
    end
  end
end

target 'ConexaSaude' do
  project 'ConexaSaude'
  workspace 'ConexaSaude'
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'
  pod 'InputMask'
  # pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  # pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'OpenTok', '2.20.0'

  pod 'RNFS', :path => '../node_modules/react-native-fs'


  pod 'opentok-react-native', :path => '../node_modules/opentok-react-native'



  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'


  target 'ConexaSaudeTests' do
    project 'ConexaSaude'
    workspace 'ConexaSaude'
    inherit! :complete
    # Pods for testing
  end

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency.podspec"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"



end

target 'ConexaSaude-tvOS' do
  project 'ConexaSaude'
  workspace 'ConexaSaude'
  # Pods for ConexaSaude-tvOS

  target 'ConexaSaude-tvOSTests' do
    project 'ConexaSaude'
    workspace 'ConexaSaude'
    inherit! :search_paths
    # Pods for testing
  end
end




post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
